### GENERAL SETTINGS ###

# Site settings
title: Bytabit
description: "The Bytabit Fiat Trader project."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "http://bytabit.org"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#C2D4E4"
  primary_rgb: "207,226,243" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#FF4B1A"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: bitbucket
    url: https://bitbucket.org/bytabit/
  - title: list-ol
    url: https://bytabit.atlassian.net/projects/FT/summary/statistics
  - title: twitter
    url: https://twitter.com/BytabitOrg
  - title: reddit-alien
    url: https://www.reddit.com/r/bytabit
  - title: comments
    url: https://bytabit.hipchat.com/chat
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Los Angeles, California, United States.
    - Bjärred , Skåne, Sweden.
email: info@bytabit.org
tel: 1.323.375.4277


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Steve Myers
    position: Co-Founder, Engineering
    text: Steve has over twenty years of professional experience in the computer industry with an emphasis in software development and high end server and network architecture. He is passionate about developing secure easy to use Bitcoin applications.
    img: steve.jpg
    social:
      - title: envelope #use for email address
        url: mailto:steve@bytabit.org
      - title: twitter
        url: http://twitter.com/stevemyers_
      - title: linkedin
        url: https://www.linkedin.com/in/smyers3
  - name: Richard Myers
    position: Co-Founder, Product Management
    text: Richard is a professional software developer with over twenty years of experience. He is an expert in all aspects of the software creation process from design and architecture through implementation, testing and support.
    img: richard.jpg
    social:
      - title: envelope #use for email address
        url: mailto:richard@bytabit.org
      - title: twitter
        url: http://twitter.com/remyers_
      - title: linkedin
        url: https://se.linkedin.com/in/remyers
  - name: Marc Lundwall
    position: Co-Founder, Business Development
    text: International Civil Servant by day and entrepreneur at heart. Believer in tapping the positive power of Bitcoin and Blockchains.
    img: marc.jpg
    social:
      - title: envelope #use for email address
        url: mailto:marc.lundwall@gmail.com
      - title: twitter
        url: twitter.com/lundwallmarc
      - title: linkedin
        url: https://www.linkedin.com/in/marc-lundwall-938a624

# Clients information. Shown on Home and About pages.
clients:
  - name: dribbble
    img: client01.png
  - name: Code is Poetry
    img: client02.png
  - name: Vimeo
    img: client03.png
  - name: VimeoPro
    img: client04.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "The mission of the Bytabit team is to provide the most secure, private, and convenient way to buy and sell fiat currency with bitcoin."

# Testimonial content. Shown on Home and About page. 
testimonial:
    message: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged."
    author: Marcel Newman
    position: WEB DESIGNER - BLACKTIE.CO